// Pro licensing for Agent Sessions.
//
// Open-core model: the Community edition is free; a few features (parallel
// comparison, launch templates, …) are gated behind a Pro licence. This module
// owns that gate — a 14-day trial plus offline licence-key verification — and
// is intentionally provider-agnostic: keys are signed by the project's private
// Ed25519 key and verified here with the embedded public key, so no licence
// server is required and any checkout platform (Lemon Squeezy / Polar /
// Gumroad) can issue keys by signing the same payload.
//
// Key format:  ATERM-PRO.<payloadB64url>.<signatureB64url>
//   payload   = JSON, e.g. {"email":"a@b.com","exp":1893456000}  (exp optional)
//   signature = Ed25519 signature over the <payloadB64url> ASCII bytes
//
// Emite/rota claves con scripts/sign-license.mjs (keygen / sign / verify). La
// privada vive en license-private.pem (gitignored); la pública va embebida
// abajo. Si LICENSE_PUBLIC_KEY queda vacío, sólo funciona el trial.

import * as crypto from "crypto";
import * as vscode from "vscode";

/** Trial length in days from first activation. */
const TRIAL_DAYS = 14;

/** Where users buy a licence. FASE 2: pon la URL real del checkout. */
export const BUY_URL = "https://aterm.dev/pro";

/** Project Ed25519 public key (SPKI DER, base64). Generated by sign-license.mjs keygen. */
const LICENSE_PUBLIC_KEY = "MCowBQYDK2VwAyEA2PfMm09hUM2rVkBaqaKiIRqNorlRPyFVbl5e4BO/RLc=";

const KEY_PREFIX = "ATERM-PRO.";
const TRIAL_START_KEY = "pro.trialStart";
const LICENSE_KEY = "pro.licenseKey";

type ProStatus = "licensed" | "trial" | "expired";

function b64urlToBuf(s: string): Buffer {
  return Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/"), "base64");
}

export class LicenseService {
  constructor(private readonly ctx: vscode.ExtensionContext) {}

  /** Start the trial clock on first run so the grace period is deterministic. */
  startTrialIfNeeded(): void {
    if (!this.ctx.globalState.get<number>(TRIAL_START_KEY)) {
      void this.ctx.globalState.update(TRIAL_START_KEY, Date.now());
    }
  }

  /** True when Pro features should be unlocked (valid licence OR active trial). */
  isPro(): boolean {
    return this.hasValidLicense() || this.inTrial();
  }

  status(): ProStatus {
    if (this.hasValidLicense()) return "licensed";
    return this.inTrial() ? "trial" : "expired";
  }

  /** Days left in the trial (0 once expired). */
  trialDaysLeft(): number {
    const start = this.ctx.globalState.get<number>(TRIAL_START_KEY);
    if (!start) return TRIAL_DAYS;
    const left = TRIAL_DAYS - Math.floor((Date.now() - start) / 86_400_000);
    return Math.max(0, left);
  }

  private inTrial(): boolean {
    return this.trialDaysLeft() > 0;
  }

  /** Verify the stored licence key against the embedded public key. */
  hasValidLicense(): boolean {
    const key = this.ctx.globalState.get<string>(LICENSE_KEY);
    return !!key && this.verify(key);
  }

  /** Validate a licence key: structure, signature and (optional) expiry. */
  verify(rawKey: string): boolean {
    const key = (rawKey || "").trim();
    if (!key.startsWith(KEY_PREFIX)) return false;
    // Without a configured public key we can't verify anything — refuse rather
    // than accept blindly (trial still covers early users).
    if (!LICENSE_PUBLIC_KEY) return false;
    const parts = key.slice(KEY_PREFIX.length).split(".");
    if (parts.length !== 2) return false;
    const [payloadB64, sigB64] = parts;
    try {
      const pub = crypto.createPublicKey({
        key: Buffer.from(LICENSE_PUBLIC_KEY, "base64"),
        format: "der",
        type: "spki",
      });
      const ok = crypto.verify(
        null,
        Buffer.from(payloadB64),
        pub,
        b64urlToBuf(sigB64)
      );
      if (!ok) return false;
      const payload = JSON.parse(b64urlToBuf(payloadB64).toString("utf8"));
      if (typeof payload.exp === "number" && Date.now() / 1000 > payload.exp) {
        return false; // expired licence
      }
      return true;
    } catch {
      return false;
    }
  }

  /** Prompt for a key, validate and store it. */
  async activate(): Promise<void> {
    const key = await vscode.window.showInputBox({
      title: "Activar licencia Pro",
      prompt: "Pega tu clave de licencia (ATERM-PRO.…)",
      ignoreFocusOut: true,
      placeHolder: "ATERM-PRO.xxxxx.yyyyy",
    });
    if (key === undefined) return;
    const trimmed = key.trim();
    if (!trimmed) {
      // Empty = deactivate.
      await this.ctx.globalState.update(LICENSE_KEY, undefined);
      vscode.window.showInformationMessage("Agent Sessions: licencia eliminada.");
      return;
    }
    if (!this.verify(trimmed)) {
      const pick = await vscode.window.showErrorMessage(
        LICENSE_PUBLIC_KEY
          ? "Agent Sessions: la clave de licencia no es válida o ha caducado."
          : "Agent Sessions: la verificación de licencias aún no está configurada en esta build.",
        "Comprar Pro"
      );
      if (pick === "Comprar Pro") void vscode.env.openExternal(vscode.Uri.parse(BUY_URL));
      return;
    }
    await this.ctx.globalState.update(LICENSE_KEY, trimmed);
    vscode.window.showInformationMessage("Agent Sessions: ¡licencia Pro activada! Gracias 🙌");
  }

  // ── QA helpers (para probar el gating sin esperar 14 días) ───────────────
  /** Force the trial to look expired and drop any licence. */
  async expireTrialForTesting(): Promise<void> {
    await this.ctx.globalState.update(
      TRIAL_START_KEY,
      Date.now() - (TRIAL_DAYS + 1) * 86_400_000
    );
    await this.ctx.globalState.update(LICENSE_KEY, undefined);
  }
  /** Restart the trial clock (also drops any licence). */
  async resetTrialForTesting(): Promise<void> {
    await this.ctx.globalState.update(TRIAL_START_KEY, Date.now());
    await this.ctx.globalState.update(LICENSE_KEY, undefined);
  }

  /** Dev-only: pick a Pro state to test the gate. */
  async debug(): Promise<void> {
    const pick = await vscode.window.showQuickPick(
      [
        { label: "$(error) Caducar prueba ahora (bloquear Pro)", action: "expire" },
        { label: "$(history) Reiniciar prueba (14 días)", action: "reset" },
        { label: "$(key) Activar licencia…", action: "activate" },
      ],
      { placeHolder: `Estado Pro actual: ${this.status()} · ${this.trialDaysLeft()} día(s)` }
    );
    if (!pick) return;
    if (pick.action === "expire") {
      await this.expireTrialForTesting();
      vscode.window.showInformationMessage("Pro: prueba caducada. Las funciones Pro están bloqueadas.");
    } else if (pick.action === "reset") {
      await this.resetTrialForTesting();
      vscode.window.showInformationMessage("Pro: prueba reiniciada (14 días).");
    } else {
      await this.activate();
    }
  }

  /** Show current Pro status and offer the relevant action. */
  async showStatus(): Promise<void> {
    const st = this.status();
    if (st === "licensed") {
      vscode.window.showInformationMessage("Agent Sessions Pro: licencia activa. ✅");
      return;
    }
    const msg =
      st === "trial"
        ? `Agent Sessions Pro: prueba activa, ${this.trialDaysLeft()} día(s) restantes.`
        : "Agent Sessions Pro: la prueba ha terminado. Las funciones Pro están bloqueadas.";
    const pick = await vscode.window.showInformationMessage(
      msg,
      "Activar licencia",
      "Comprar Pro"
    );
    if (pick === "Activar licencia") await this.activate();
    else if (pick === "Comprar Pro") void vscode.env.openExternal(vscode.Uri.parse(BUY_URL));
  }
}
